
# services:
#   backend:
#     build: ./Backend
#     ports:
#       - "8889:8889"

#   frontend:
#     build: ./Frontend
#     ports:
#       - "8501:8501"
#     depends_on:
#       - backend

#backend and frontend serveices are build when given their folders(and Dockerfile names) , on which ports do they run and if any service depend on another
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8889:8889"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend

#docker compose build  
#docker compose up --build ..it builds & runs services of docker compose
#docker compose up -d .. it starts container and you can see in docker desktop
